chiainit: lots of changes in the output display and error handling. standard  output is minimized and made more beautiful. details in standard output only displayed for errors. logfile still captures everything

diff --git a/chiainit/chiainit b/chiainit/chiainit
--- a/chiainit/chiainit
+++ b/chiainit/chiainit
@@ -16,9 +16,23 @@ RED="\033[31m"
 BOLD="\033[1m"
 RESET="\033[0m"
 
-VERSION="V2.1"
+VERSION="V2.2"
 ACTION=""
 FSTYPE=""
+
+# Default log file location
+logfile="./chiainit.log"
+
+# Function to prepend timestamp to each line of output
+prepend_timestamp() {
+    while IFS= read -r line; do
+        echo "$(date '+%Y-%m-%d %H:%M:%S') $line"
+    done
+}
+
+# Redirect both stdout and stderr, adding timestamps for the logfile
+exec > >(tee >(prepend_timestamp >> "$logfile")) 2> >(tee >(prepend_timestamp >> "$logfile") >&2)
+
 
 # Function to retrieve the serial number of a drive
 get_serial_number() {
@@ -37,7 +51,7 @@ get_uuid() {
     partition=$1
     uuid=$(sudo blkid -o value -s UUID /dev/$partition)
     if [ -z "$uuid" ]; then
-        echo "UNKNOWN"
+        echo "could not get UUID"
     else
         echo "$uuid"
     fi
@@ -105,35 +119,38 @@ summarize_actions() {
 # Function to label a drive
 label() {
     drive=$1
-    partition=$2
-    serial_number=$(get_serial_number "$drive")
-    uuid=$(get_uuid "$partition")
-    echo "  Serial Number: $serial_number"
-    echo "  UUID: $uuid"
-    
-    if [ "$serial_number" == "UNKNOWN" ]; then
-        serial_number=$uuid
-    fi
-    label="${SERIALPREFIX}-${serial_number}"
-    FSTYPE=$(get_fs_type "$partition")
+    partition="${drive}1"
 
-    case "$FSTYPE" in
-        xfs)
-            label=$(echo "$label" | cut -c 1-12)
-            echo "  setting filesystem: xfs"
-            sudo xfs_admin -L "$label" /dev/$partition
-            ;;
-        ext4)
-            label=$(echo "$label" | cut -c 1-16)
-            echo "  setting filesystem: ext4"
-            sudo e2label /dev/$partition "$label"
-            ;;
-        ntfs)
-            label=$(echo "$label" | cut -c 1-32)
-            echo "  setting filesystem: ntfs"
-            sudo ntfslabel /dev/$partition "$label"
-            ;;
-    esac
+    # Perform labeling and direct output to the logfile
+    {
+        echo -e "\n${BOLD}Labeling /dev/$partition${RESET}"
+        serial_number=$(get_serial_number "$drive")
+        uuid=$(get_uuid "$partition")
+        
+        if [ "$serial_number" == "UNKNOWN" ]; then
+            serial_number=$uuid
+        fi
+        label="${SERIALPREFIX}-${serial_number}"
+        FSTYPE=$(get_fs_type "$partition")
+
+        case "$FSTYPE" in
+            xfs)
+                label=$(echo "$label" | cut -c 1-12)
+                sudo xfs_admin -L "$label" /dev/$partition
+                ;;
+            ext4)
+                label=$(echo "$label" | cut -c 1-16)
+                sudo e2label /dev/$partition "$label"
+                ;;
+            ntfs)
+                label=$(echo "$label" | cut -c 1-32)
+                sudo ntfslabel /dev/$partition "$label"
+                ;;
+        esac
+    } &>> "$logfile"
+
+    local exit_status=$?
+    return $exit_status
 }
 
 
@@ -161,9 +178,11 @@ get_label() {
 # Function to wipe a drive
 wipe() {
     drive=$1
-    sudo wipefs -a /dev/$drive 2>&1
-    #sudo dd if=/dev/zero of=/dev/$drive bs=1M count=100
-}    
+    sudo wipefs -a /dev/$drive
+    local exit_status=$?
+    return $exit_status
+}
+
 
 # Function to format a drive
 format() {
@@ -172,22 +191,22 @@ format() {
         return
     fi
 
-    #echo -e "g\nn\n1\n\n\nw" | sudo fdisk /dev/$drive 2>&1
     partition="${drive}1"
-    if [ "$FSTYPE" == "xfs" ]; then
-        sudo parted /dev/$drive --script mklabel gpt mkpart primary xfs 0% 100%
+
+    # Partition, sync, and format the drive
+        sudo parted /dev/$drive --script mklabel gpt mkpart primary $FSTYPE 0% 100%
         sudo sync
-        sudo mkfs.xfs ${XFSOPTIONS} /dev/$partition 2>&1
-    elif [ "$FSTYPE" == "ext4" ]; then
-        sudo parted /dev/$drive --script mklabel gpt mkpart primary ext4 0% 100%
-        sudo sync
-        sudo mkfs.ext4 ${EXT4OPTIONS} /dev/$partition 2>&1
-    elif [ "$FSTYPE" == "ntfs" ]; then
-        sudo parted /dev/$drive --script mklabel gpt mkpart primary ntfs 0% 100%
-        sudo sync
-        sudo mkfs.ntfs ${NTFSOPTIONS} /dev/$partition 2>&1
-    fi
-}    
+        if [ "$FSTYPE" == "xfs" ]; then
+            sudo mkfs.xfs ${XFSOPTIONS} /dev/$partition
+        elif [ "$FSTYPE" == "ext4" ]; then
+            sudo mkfs.ext4 ${EXT4OPTIONS} /dev/$partition
+        elif [ "$FSTYPE" == "ntfs" ]; then
+            sudo mkfs.ntfs ${NTFSOPTIONS} /dev/$partition
+        fi
+
+    local exit_status=$?
+    return $exit_status
+}
 
 
 # Function to initialize a drive (wipe, format, and label)
@@ -228,6 +247,7 @@ increment_drive() {
     fi
 }
 
+
 expand_drive_range() {
     local range="$1"
     local prefix="sd"
@@ -248,7 +268,6 @@ expand_drive_range() {
     done
     echo "${prefix}${current_drive}"
 }
-
 
 
 
@@ -310,7 +329,7 @@ display_help() {
     echo "  --init                    : Wipe, format, and label the specified drives (requires --fstype)"
     echo "  --fstype [xfs|ext4|ntfs]  : Specify the filesystem type"
     echo "  --label-prefix PREFIX     : Specify a custom prefix for the drive labels (default: CHIA)"
-    echo "  --all                     : Operate on all drives (excluding system drive and mounted drives)"
+    echo "  --all                     : Operate on all drives (excluding system drives)"
     echo "  --exclude [drive1 drive2] : Exclude the specified drives from the operation"
     echo ""
     echo "Examples:"
@@ -334,49 +353,95 @@ display_version() {
 }
 
 
+
 # Spinner code
-spinner() {
-    local pid=$1
-    local delay=0.05
-    local spinstr='|/-\'
-    while pgrep -x -P $pid > /dev/null; do
-        local temp=${spinstr#?}
-        printf " [%c]  " "$spinstr"
-        local spinstr=$temp${spinstr%"$temp"}
-        sleep $delay
-        printf "\b\b\b\b\b\b"
-    done
-    printf "    \b\b\b\b"
-    echo -e "${GREEN}OK${RESET}"
+spinner=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
+export spin=true
+
+start_spinner() {
+    local message=$1
+    spin=true
+    tput civis # Hide cursor
+
+    while $spin; do
+        for i in "${spinner[@]}"; do
+            printf "\r$i $message"
+            sleep 0.1
+        done
+    done &
+    spinner_pid=$!
 }
+
+stop_spinner() {
+    # Kill the spinner process
+    if [ ! -z "$spinner_pid" ]; then
+        kill "$spinner_pid" 2>/dev/null
+    fi
+    tput cnorm # Show cursor
+    printf "\r%s\r" "$(printf ' %.0s' {1..50})" # Clear line
+}
+
 
 
 # Execute action
 execute_action() {
     action=$1
     drive=$2
+    local output
+    local exit_status
+
     case "$action" in
         --init)
-            echo -e "\n${BOLD}${CYAN}Drive /dev/$drive:${RESET}"
+            echo -e "\n${BOLD}${CYAN}[+] Drive /dev/$drive${RESET}"
             init $drive
             ;;
         --wipe)
-            echo -e "  ${YELLOW}Wiping /dev/$drive...${RESET}"
-            wipe $drive
+            start_spinner "/dev/$drive wiping"
+            output=$(wipe $drive 2>&1)
+            exit_status=$?
+            stop_spinner
+            if [ $exit_status -eq 0 ]; then
+                echo -e "\e[32m✔\e[0m ${CYAN}/dev/$drive${RESET} wiping...... ${GREEN}ok${RESET}"
+            else
+                echo -e "\e[31m✖\e[0m ${CYAN}/dev/$drive${RESET} wiping...... ${RED}failed${RESET}"
+                echo "$output"
+            fi
+            echo -e "\n$output" >> "$logfile"  # Log output irrespective of success or failure
             ;;
         --format)
-            echo -e "  ${YELLOW}Formatting /dev/$drive...${RESET}"
-            format $drive
+            start_spinner "/dev/$drive formatting"
+            output=$(format $drive 2>&1)
+            exit_status=$?
+            stop_spinner
+            if [ $exit_status -eq 0 ]; then
+                actual_fstype=$(get_fs_type "${drive}1")
+                echo -e "\e[32m✔\e[0m ${CYAN}/dev/$drive${RESET} formatting.. ${GREEN}$actual_fstype${RESET}"
+            else
+                echo -e "\e[31m✖\e[0m ${CYAN}/dev/$drive${RESET} formatting.. ${RED}failed${RESET}"
+                echo "$output"
+            fi
+            echo "$output" >> "$logfile"  # Log output irrespective of success or failure
             ;;
         --label)
-            echo -e "  ${YELLOW}Labeling /dev/${drive}1...${RESET}"
+            start_spinner "/dev/$drive labelling"
             partition="${drive}1"
-            label $drive "$partition"
-            drive_label=$(get_label "$partition")
-            echo -e "  ${CYAN}New label: ${RESET}${drive_label}"
+            output=$(label $drive "$partition" 2>&1)
+            exit_status=$?
+            stop_spinner
+            echo "$output" >> "$logfile"  # Log output irrespective of success or failure
+            if [ $exit_status -eq 0 ]; then
+                actual_label=$(get_label "$partition")
+                echo -e "\e[32m✔\e[0m ${CYAN}/dev/$drive${RESET} labeling.... ${GREEN}${actual_label}${RESET}"
+            else
+                echo -e "\e[31m✖\e[0m ${CYAN}/dev/$drive${RESET} labeling.... ${RED}failed${RESET}"
+                echo "$output"
+            fi
+            echo "$output" >> "$logfile"  # Log output irrespective of success or failure
             ;;
+            
     esac
 }
+
 
 declare -a drives=()
 
@@ -446,9 +511,9 @@ for i in "${!DRIVES[@]}"; do
     if is_system_drive "${DRIVES[$i]}"; then
         echo -e "${YELLOW}INFO:${RESET} Drive ${BOLD}${DRIVES[$i]}${RESET} is a system drive. Excluding from operation."
         is_excluded=true
-    elif is_drive_mounted "${DRIVES[$i]}"; then
-        echo -e "${YELLOW}INFO:${RESET} Drive ${BOLD}${DRIVES[$i]}${RESET} is mounted. Excluding from operation."
-        is_excluded=true
+    #elif is_drive_mounted "${DRIVES[$i]}"; then
+    #    echo -e "${YELLOW}INFO:${RESET} Drive ${BOLD}${DRIVES[$i]}${RESET} is mounted. Excluding from operation."
+    #    is_excluded=true
     elif [[ " ${EXCLUDED_DRIVES[*]} " == *"${DRIVES[$i]}"* ]]; then
         echo -e "${YELLOW}INFO:${RESET} Drive ${BOLD}${DRIVES[$i]}${RESET} is manually excluded. Excluding from operation."
         is_excluded=true
@@ -464,7 +529,8 @@ NON_EXCLUDED_DRIVES=()
 
 # Filter out the system drive, mounted drives, and user-excluded drives
 for drive in "${DRIVES[@]}"; do
-    if is_system_drive "$drive" || is_drive_mounted "$drive" || [[ " ${EXCLUDED_DRIVES[*]} " == *"$drive"* ]]; then
+    #if is_system_drive "$drive" || is_drive_mounted "$drive" || [[ " ${EXCLUDED_DRIVES[*]} " == *"$drive"* ]]; then
+    if is_system_drive "$drive" || [[ " ${EXCLUDED_DRIVES[*]} " == *"$drive"* ]]; then
         # Drive is excluded, do nothing
         :
     else
@@ -483,10 +549,10 @@ summarize_actions
 
 
 # Check for and confirm destructive actions
-if [ "$ACTION" == "--wipe" ] || [ "$ACTION" == "--format" ] || [ "$ACTION" == "--init" ]; then
-    confirm_destructive_action "${DRIVES[@]}"
-    #echo ""
-fi
+# if [ "$ACTION" == "--wipe" ] || [ "$ACTION" == "--format" ] || [ "$ACTION" == "--init" ]; then
+#    confirm_destructive_action "${DRIVES[@]}"
+#    #echo ""
+# fi
 
 
 for drive in "${DRIVES[@]}"; do
@@ -497,8 +563,6 @@ for drive in "${DRIVES[@]}"; do
     fi
     execute_action "$ACTION" $drive
 done
-
-
 
 echo -e "\nOperation complete for all specified drives.\n"
 
